### ISSUE TITLE
Feature Request: Add composer.json

### ISSUE THREAD

**Issue by winkelsdorf** [fbrnc/Aoe_CacheCleaner#6]
If it's still usable with 1.9.x (i see no problems during my tests), I would suggest to add a composer.json to this project.

**Comment by fbrnc** [comment]
Hi,

sadly this is a very old version that I didn't cleanup. Please check https://github.com/aoepeople/Aoe_CacheCleaner for the latest version (that also comes with a composer.json)

**Comment by fbrnc** [comment]
Actually, I'm going to delete this repository now...
